---
applications:
- name: gs-rest-service
  memory: 256M
  instances: 1
  host: rest-service
  domain: guides.spring.io

server:
  port: 9000

pattern:
  servlet-url-pattern: /hello-world/api/*
  

logging:
  config: config/logback.xml

endpoints:
  shutdown:
    enabled: true
    sensitive: false

management:
  context-path: /management
  port: 9001
  address: 127.0.0.1

